language: java
deploy:
  provider: heroku
  api_key:
    secure: d6kVJvFeeTX84ZqESJ/zGmlt+7f7b1105KjcqjCkcuiffBUzxNoH9TVEtXfLBf142NhiNur8YZmISZOTX3gKSXsvRvp7bDCsc7iwif/1biMzD9bZRtpKdVy00zTnCt5U60tBfZt0WIIsMcARE7rC5LP3OfTG0qA4+wXbc26YDgVP+OrQXgt0YlnWdAeTFbdFMgxtj1WJKIqFi0iQw0FUI1Rpg1KifF84jCum+tKHJY9FQP378Eb3ORr9qPAgbpPUadN3ACjJLDWADzdLBPoO1WKLYMJYiJFbbNKBMpjDlC42aqFz8hABL5Ha3+A+gdjnJzbNOXWbZROxpUcFrY3BB4JQv0y8iNNgPC5/iRJL87/7ejbAMkVcz5pBTIopStRnVU/FNJhOZzYD3I6epVhma4I58m0vGavYi9+140/aS9EtYoZpLDx1li4UVirFQ1pHo4FkGtUkxcVqoTeYIxpYBZXT/a4MzvlQRkph9ce1ja0xEoqW345fTDapJE9mTRz3ZX9V7avhhymes0l59h33CwskmojfAHKJmCGFOKbH6cuOPGQZOTzu1/ZtX8zDAhgYSECOKoEOuh2Ij6hwzvzcXPg3qLbTy0nNr46AW/+cjAXvhfYrVwGAIhhklC9AUBTHSTqdC6mf7r2BVK4c6ecwkRVt7SbslsunyjqaQGEAINo=
  app: aliveapplication
