language: java
deploy:
  provider: heroku
  api_key:
    secure: "ZAAU6FPlqPf7d8NbxTX17uJRVpV+zxhN5WPOHp5PsuDbKppFJoIhjamWVrNMZESaFz1tfL8+S4fgsc8iCC9xmHZCPxyHJGf56597tCH+dbElATPaB2eI0XtnHkJQdteWGedxhv02QaHCLYaQX1d6yI2dR8pnp2Lbr4VwjoEFJtwiic93gdiTgJdVnluJUJsBu/JnZ+2BRMdRVZq/OhTQVMjjcwaDa2MbfWcTR4FkW68O+CdvB2UOq1oUe2l8RzDnA/f3POZNzk65xwb4yGDRhVnTwYjK7OJbfLj0KDdit8lShS9OX0h32jP4roRPiiHxnVc4XHC2tTaiJY/2+CXUdlWpvN9bVQFK5gUhrXqfAJzCQHAqJ4IXy9/4fBZT5/Yp2k4fXkhttI4kPpT25HDEbu9UVHQ1pIUY/XyM38l8MeUkprCCb5w6rRpVgDPNi5AJ0xgX95TXSUZf2YBa/1WuHaUYXt4O38Un7iF1sKj6AzmBUju3ZLni5b25SNCViZhH26DCZDEUtT9b0D0yfpGhbZ6WAEWSyjZjcnplMqN3V06itpSXqPrO/ZlRZWNRHQnWS8ODXtrkIrWsLD9eJRa+QbX3yb/fwyfvHfWw0Yzg3ekH/uY1nQYfEVjI1eRD6rqbkzJGzxK5m18fYKfntaSKkiFI4n9nt+6KhfSVpKXk86U="
  app: aliveapplication
  
  
  